<!-- common header -->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Monitor Systems Control Center</title>

  <link href="css/bootstrap-clockpicker.min.css"  rel="stylesheet" />
  <link href="css/fonts.css" rel="stylesheet" />
  <link href="css/morris.css"  rel="stylesheet" />
  <link href="css/datepicker3.css" rel="stylesheet" />
  <link href="css/jquery.bootstrap-touchspin.min.css" rel="stylesheet" />
  <link href="css/main.css" rel="stylesheet" />
  <link href="css/jquery-ui.min.css" rel="stylesheet" />
  <link href="css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
  <link href="css/theme" rel="stylesheet" />  <!-- 1 7 6 3 4 5-->
  <link rel="stylesheet" href="css/bitmap-fonts.css">
  <link rel="stylesheet" href="css/datepicker3.css">
  <link rel="stylesheet" href="css/jreject.css">
  <link rel="stylesheet" href="css/bootstrap-clockpicker.min.css">
  

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="js/html5shiv.min.js"></script>
    <script src="js/respond.min.js"></script>
  <![endif]-->

</head>
